aka3 = list(
    Histology   = c(
        Pancreatic_NEN = "BLACK",
        Colorectal_NEN = "Orange",
        Small_intestinal_NEN = "Yellow",
        Gastric_NEN = "purple",
        Liver = "Darkgreen",
        CUP = "pink"),
    Deco_type = c(alpha = "Blue",beta = "Yellow",gamma = "Orange",delta = "Purple", e13.5 = "Brown", hsc = "white"),
    NEC_NET = c(NEC= "red", NET = "blue", "NA" = "white"),
    Study = c(Groetzinger = "brown", Scarpa = "darkgreen"),
    MKI67 = c(high = "White", medium = "gray", low = "black"),
    INS = c(high = "White", low = "yellow"),
    Correlation = c(high = "Red", medium = "Yellow", low = "Green"),
    Deco_similarity = c(low = "Red", medium = "Yellow", high = "Green"),
    ImmuneScore = c(high = "White", medium = "gray", low = "Black"),
    StromalScore = c(high = "White", medium = "gray", low = "Black"),
    alpha_similarity = c(low = "white", high = "blue",not_sig = "gray"),
    beta_similarity = c(low = "white", high = "darkgreen",not_sig = "gray"),
    gamma_similarity = c(low = "white", high = "orange",not_sig = "gray"),
    delta_similarity = c(low = "white", high = "Purple",not_sig = "gray"),
    ductal_similarity = c(low = "white", high = "Black",not_sig = "gray"),
    accinar_similarity = c(low = "white", high = "Brown",not_sig = "gray"),
    Progenitor_similarity = c(low = "white", high = "darkred",not_sig = "gray"),
    Differentiated_similarity= c(low = "white", high = "darkgreen",not_sig = "gray"),
    Diff_Type_Three = c(Differentiated = "darkgreen", Progenitor = "Brown", HESC = "Black"),
    HISC_similarity = c(low = "white", high = "black",not_sig = "gray"),
    HESC_similarity = c(low = "white", high = "black",not_sig = "gray"),
    Marker_Genes = c(high = "White", medium = "Yellow", low = "Red"),
    Functionality = c( Unknown = "White",Functional = "green", Non_Functional="red"),
    Grading = c( G1 = "Green",G2 = "Yellow", G3 = "Red", G0 = "white"),
    Subtype_Sadanandam = c(Norm = "darkgreen", Insulinoma = "Blue", MLP = "Orange", Intermediate = "brown", Unknown = "White"),
    #Differentiation_type = c( Differentiated = "green", Progenitor = "orange", HESC = "brown", not_sig = "gray")
    Differentiation_type = c( Alpha = "blue", Beta ="green", Gamma = "Orange", Delta = "Purple", Progenitor = "Yellow", HESC = "brown", not_sig = "gray"),
    De_differentation_score = c(low = "red", medium = "white", high = "green"),
    Differentation_score = c(low = "red", medium = "white", high = "green"),
    Differentiation_Stage_Aggregated = c(
        differentiated = "darkgreen",
        stem_cell = "red",
        progenitor     = "orange",
        Not_significant= "gray"
    )
)
